# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollView的自动布局以及IphoneX适配' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry'

  # Pods for ScrollView的自动布局以及IphoneX适配

end
